export const countries = [
  { name: 'Nigeria', flag: '🇳🇬', languages: ['en'] },
  { name: 'Japan', flag: '🇯🇵', languages: ['ja'] },
  { name: 'Spain', flag: '🇪🇸', languages: ['es'] },
  { name: 'Germany', flag: '🇩🇪', languages: ['de'] },
  { name: 'Italy', flag: '🇮🇹', languages: ['it'] },
  { name: 'UAE', flag: '🇦🇪', languages: ['ar'] },
  { name: 'India', flag: '🇮🇳', languages: ['hi', 'en'] },
  { name: 'China', flag: '🇨🇳', languages: ['zh'] },
  { name: 'Netherlands', flag: '🇳🇱', languages: ['nl'] },
  { name: 'South Korea', flag: '🇰🇷', languages: ['ko'] },
  { name: 'Belgium', flag: '🇧🇪', languages: ['nl', 'fr', 'de'] },
  { name: 'Switzerland', flag: '🇨🇭', languages: ['de', 'fr', 'it', 'rm'] },
  { name: 'Turkey', flag: '🇹🇷', languages: ['tr'] },
  { name: 'Brazil', flag: '🇧🇷', languages: ['pt'] },
  { name: 'Saudi Arabia', flag: '🇸🇦', languages: ['ar'] },
  { name: 'Thailand', flag: '🇹🇭', languages: ['th'] },
  { name: 'Indonesia', flag: '🇮🇩', languages: ['id'] },
  { name: 'Malaysia', flag: '🇲🇾', languages: ['ms'] },
  { name: 'Tanzania', flag: '🇹🇿', languages: ['sw', 'en'] },
  { name: 'Ghana', flag: '🇬🇭', languages: ['en'] },
  { name: 'Cameroon', flag: '🇨🇲', languages: ['fr', 'en'] },
  { name: 'Morocco', flag: '🇲🇦', languages: ['ar', 'ber'] },
  { name: 'South Africa', flag: '🇿🇦', languages: ['en', 'zu', 'xh', 'af'] },
  { name: 'Namibia', flag: '🇳🇦', languages: ['en'] },
  { name: 'Gabon', flag: '🇬🇦', languages: ['fr'] },
  { name: 'Guinea', flag: '🇬🇳', languages: ['fr'] },
  { name: 'Congo', flag: '🇨🇬', languages: ['fr'] },
  { name: 'Zambia', flag: '🇿🇲', languages: ['en'] },
  { name: 'Malawi', flag: '🇲🇼', languages: ['en'] },
  { name: 'Rwanda', flag: '🇷🇼', languages: ['rw', 'fr', 'en', 'sw'] },
  { name: 'Kenya', flag: '🇰🇪', languages: ['en', 'sw'] },
  { name: 'Botswana', flag: '🇧🇼', languages: ['en'] },
  { name: 'Ethiopia', flag: '🇪🇹', languages: ['am'] },
  { name: 'Algeria', flag: '🇩🇿', languages: ['ar', 'ber'] },
  { name: 'Libya', flag: '🇱🇾', languages: ['ar'] },
  { name: 'Zimbabwe', flag: '🇿🇼', languages: ['en'] },
  { name: 'Uganda', flag: '🇺🇬', languages: ['en', 'sw'] },
  { name: 'Burkina Faso', flag: '🇧🇫', languages: ['fr'] },
  { name: 'Benin', flag: '🇧🇯', languages: ['fr'] },
  { name: 'Lesotho', flag: '🇱🇸', languages: ['st', 'en'] },
  { name: 'Sudan', flag: '🇸🇩', languages: ['ar', 'en'] },
  { name: 'Mali', flag: '🇲🇱', languages: ['fr'] },
];
